#!/bin/sh

set -e
umask 022

echo "FETCH: kernel"

[ -z "$KERNEL_LINUX_VERSION" ] && echo 'error: Expected $KERNEL_LINUX_VERSION' && exit 1

cd workbench

echo "- Fetching latest kernel"
if [ ! -d kernel ]
then
	git clone 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git' kernel
	touch kernel-latest
fi

cd kernel
git fetch --all
git checkout "v$KERNEL_LINUX_VERSION"
cd ..

echo "- Fetching HeylelOS initramfs"
if [ ! -d initramfs ]
then
	git clone 'https://github.com/HeylelOS/initramfs' initramfs
	touch initramfs-latest
fi

cd initramfs
git fetch --all
cd ..

