#!/bin/sh

set -e
umask 022

echo "PACKAGE: init"

[ -z "$INIT_CYBERD_VERSION" ] && echo 'error: Expected $INIT_CYBERD_VERSION' && exit 1
[ -z "$ALL_TARGET_IDENTIFIER" ] && echo 'error: Expected $ALL_TARGET_IDENTIFIER' && exit 1

cd products

echo "- Packaging init"
packagename="cyberd-$INIT_CYBERD_VERSION.hny"
if [ -f $packagename ]
then echo "- init package is up-to-date"
else
	if [ $INIT_CYBERD_VERSION != "`cat ../workbench/init-latest`" ]
	then echo "- Built version differs from packaging one, aborting..." && exit 1
	fi

	[ ! -d init ] && mkdir init

	interp="/library/$ALL_TARGET_IDENTIFIER/ld.so"

	../tools/objconvert "$interp" ../workbench/init/build/bin/cyberd init/cyberd
	../tools/objconvert "$interp" ../workbench/init/build/bin/cyberctl init/cyberctl

	rm -f init/package.cpio
	../tools/cpio-entry -m 040755 -u 0 -g 0 bin >> init/package.cpio
	../tools/cpio-entry -m 100755 -u 0 -g 0 bin/cyberd init/cyberd >> init/package.cpio
	../tools/cpio-entry -m 100755 -u 0 -g 0 bin/cyberctl init/cyberctl >> init/package.cpio
	../tools/cpio-entry -m 040755 -u 0 -g 0 man >> init/package.cpio
	../tools/cpio-entry -m 100644 -u 0 -g 0 man/cyberd.1 ../workbench/init/man/cyberd.1 >> init/package.cpio
	../tools/cpio-entry -m 100644 -u 0 -g 0 man/cyberctl.1 ../workbench/init/man/cyberctl.1 >> init/package.cpio
	../tools/cpio-entry -m 040755 -u 0 -g 0 hny >> init/package.cpio
	../tools/cpio-entry -m 100755 -u 0 -g 0 hny/setup ../ingredients/init-hny-setup >> init/package.cpio
	../tools/cpio-entry -m 100755 -u 0 -g 0 hny/clean ../ingredients/init-hny-clean >> init/package.cpio
	../tools/cpio-entry -m 100644 -u 0 -g 0 hny/eula ../workbench/init/LICENSE >> init/package.cpio
	../tools/cpio-entry -u 0 -g 0 'TRAILER!!!' >> init/package.cpio

	if xz -C none --lzma2 < init/package.cpio > $packagename
	then echo "- $packagename successfully packaged"
	else
		echo "- Unable to package $packagename"
		rm $packagename
		exit 1
	fi
fi

