#!/bin/sh

set -e
umask 022

# Machine Target specific
environment='x86_64-linux-musl'
hostname=heylelos

[ ! -d builds ] && mkdir builds
CC=clang CFLAGS='-O3 -rtlib=compiler-rt' \
./build-libc '1.1.22' $environment
./build-kernel '5.2' $hostname
#./build-utilities
#./build-init
./build-image $hostname

