#!/bin/sh

set -e

echo "Setup $HNY_ENTRY"

if [ `id -u` -ne 0 ]
then
	echo "This program must be run as root"
	exit 1
fi

ln -fs "$HNY_PREFIX/$HNY_ENTRY/bin/cyberd" /sbin/init
ln -fs "$HNY_PREFIX/$HNY_ENTRY/bin/cyberctl" /bin/cyberctl
[ ! -d /data/daemons ] && mkdir /data/daemons

