#!/bin/sh

set -e

echo "Setup cyberd"

if [ `id -u` -ne 0 ]
then
	echo "This program must be run as root"
	exit "$HNY_ERROR_UNAUTHORIZED"
fi

ln -fs "$HNY_PREFIX/bin/cyberd" /sbin/init
ln -fs "$HNY_PREFIX/bin/cyberctl" /bin/cyberctl
[ ! -d /persistent/daemons ] && mkdir /persistent/daemons

