#!/bin/sh

[ $# -ne 3 ] && echo "usage: $0 <interp> <source> <destination>" && exit 1
[ -z "$TEMPDIR" ] && export TEMPDIR=/tmp

if interp=`mktemp -p "$TEMPDIR" objconvert-interp.XXXXXX`
then
	printf "$1\0" >> "$interp"
	shift
	objcopy -S --update-section ".interp=$interp" -- $@
	rm "$interp"
fi

